title: Fariah Jannat
Description: I'm a sophomore at Lawrence University. I'm majoring in Neuroscience with a minor in Data Science. 
remote_theme: pages-themes/minimal@v0.2.0
plugins: 
 - jekyll-remote-theme
